openapi: 3.0.3
info:
  title: Inventory API
  version: 1.0.0
  description: API РґР»СЏ СѓРїСЂР°РІР»РµРЅРёСЏ РѕР±СЉРµРєС‚Р°РјРё, РѕР±РѕСЂСѓРґРѕРІР°РЅРёРµРј, Р·Р°РґР°С‡Р°РјРё Рё СЃРѕРѕР±С‰РµРЅРёСЏРјРё С‡Р°С‚Р°.
servers:
  - url: https://{project}.functions.supabase.co
    variables:
      project:
        default: your-project-ref
paths:
  /export/{table}/{format}:
    get:
      summary: Р­РєСЃРїРѕСЂС‚ РґР°РЅРЅС‹С… С‚Р°Р±Р»РёС†С‹ РІ CSV/XLSX
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: format
          in: path
          required: true
          schema:
            type: string
            enum: [csv, xlsx]
        - name: columns
          in: query
          required: false
          schema:
            type: string
            description: РЎРїРёСЃРѕРє СЃС‚РѕР»Р±С†РѕРІ С‡РµСЂРµР· Р·Р°РїСЏС‚СѓСЋ
      responses:
        "200":
          description: РЈСЃРїРµС€РЅС‹Р№ СЌРєСЃРїРѕСЂС‚
          content:
            text/csv: {}
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: {}
  /import:
    post:
      summary: РРјРїРѕСЂС‚ РґР°РЅРЅС‹С… РёР· С„Р°Р№Р»Р° РІ С‚Р°Р±Р»РёС†Сѓ
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                table:
                  type: string
                file:
                  type: string
                  format: binary
              required: [table, file]
      responses:
        "200":
          description: Р РµР·СѓР»СЊС‚Р°С‚ РёРјРїРѕСЂС‚Р°
          content:
            application/json:
              schema:
                type: object
                properties:
                  inserted:
                    type: integer
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        row:
                          type: integer
                        error:
                          type: string
  /import-export:
    get:
      summary: РџСЂРѕРІРµСЂРєР° РґРѕСЃС‚СѓРїРЅРѕСЃС‚Рё С„СѓРЅРєС†РёР№ РёРјРїРѕСЂС‚Р°/СЌРєСЃРїРѕСЂС‚Р°
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


