openapi: 3.0.3
info:
  title: Inventory App API
  version: 1.0.0
  description: API для приложения учёта объектов, оборудования и задач
servers:
  - url: https://{project}.supabase.co/functions/v1
    variables:
      project:
        default: YOUR_PROJECT_REF
paths:
components:
  schemas:
    Object:
      type: object
      required:
        - id
        - name
        - created_at
      properties:
        id:
          type: integer
          description: Уникальный идентификатор объекта
        name:
          type: string
          description: Название объекта
        description:
          type: string
          description: Описание объекта
          nullable: true
        created_at:
          type: string
          format: date-time
          description: Дата и время создания
    Hardware:
      type: object
      required:
        - id
        - object_id
        - name
        - created_at
      properties:
        id:
          type: integer
          description: Уникальный идентификатор оборудования
        object_id:
          type: integer
          description: Идентификатор связанного объекта
        name:
          type: string
          description: Название оборудования
        location:
          type: string
          description: Местоположение оборудования
          nullable: true
        purchase_status:
          type: string
          description: Статус закупки
          enum:
            - "не заказано"
            - "заказано"
            - "доставлено"
          nullable: true
        install_status:
          type: string
          description: Статус установки
          enum:
            - "не установлено"
            - "установлено"
            - "настроено"
          nullable: true
        created_at:
          type: string
          format: date-time
          description: Дата и время создания
    Task:
      type: object
      required:
        - id
        - object_id
        - title
        - status
        - created_at
      properties:
        id:
          type: integer
          description: Уникальный идентификатор задачи
        object_id:
          type: integer
          description: Идентификатор связанного объекта
        title:
          type: string
          description: Заголовок задачи
        status:
          type: string
          description: Статус задачи
          enum:
            - "запланировано"
            - "в процессе"
            - "завершено"
        assignee:
          type: string
          description: Имя исполнителя
          nullable: true
        assignee_id:
          type: string
          description: Идентификатор исполнителя
          nullable: true
        due_date:
          type: string
          format: date-time
          description: Срок выполнения
          nullable: true
        notes:
          type: string
          description: Дополнительные заметки
          nullable: true
        created_at:
          type: string
          format: date-time
          description: Дата и время создания
    ChatMessage:
      type: object
      required:
        - id
        - object_id
        - sender
        - content
        - created_at
      properties:
        id:
          type: integer
          description: Уникальный идентификатор сообщения
        object_id:
          type: integer
          description: Идентификатор связанного объекта
        sender:
          type: string
          description: E-mail отправителя
        content:
          type: string
          description: Текст сообщения
        file_url:
          type: string
          format: uri
          description: Ссылка на вложенный файл
          nullable: true
        created_at:
          type: string
          format: date-time
          description: Дата и время отправки
        read_at:
          type: string
          format: date-time
          description: Дата и время чтения
          nullable: true